### ISSUE TITLE
There is no support on RTL

### ISSUE THREAD

**Issue by idanlevi1** [daroldso/react-native-comparison-table#2]
Do you have a plan to support on Right-To_left direction?

**Comment by daroldso** [comment]
There is no plan to support RTL at the moment. PR is welcomed :)

**Comment by daroldso** [comment]
There is no plan to support RTL at the moment. PR is welcomed 🙂

**Comment by idanlevi1** [comment]
> There is no plan to support RTL at the moment. PR is welcomed 🙂

On the way :)

**Comment by idanlevi1** [comment]
PR - #3
